name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: easypi/scrapyd
          options: -v ${{ github.workspace }}:/work -w /work
          run: ./run.sh
      - shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'nothing to commit'
          else
            git add archives
            git commit -m "updated at $(date +%FT%T)"
            git push
          fi
      - shell: bash
        run: |
          curl -sSL https://api.github.com/repos/easydata/utopia/commits/HEAD \
            | jq -e 'now-(.commit.author.date|fromdateiso8601)<3600*24'
      - if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: github
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "text": "Too Bad",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ],
                  "footer": "Github Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
