name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: easypi/scrapyd
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          for city in beijing shanghai shenzhen; do
            mkdir -p archives/$city
            output="archives/$city/$(date +%F).jsonl"
            scrapy runspider spiders/$city.py -o $output:jsonlines
            if [[ -s $output ]]; then
              gzip -f $output
              echo "OK: $city"
            else
              rm -f $output
              echo "ERROR: $city"
            fi
          done
      - shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'nothing to commit'
          else
            git add archives
            git commit -m "updated at $(date +%FT%T)"
            git push
          fi
